name: main

on:
  push:
    branches: [ main ]


jobs:
  build:
    name: pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install sbot
        run: SEMVERBOT_VERSION=1.1.0
          mkdir bin
          echo "$(pwd)/bin" >> $GITHUB_PATH
          curl -o bin/sbot -L https://github.com/restechnica/semverbot/releases/download/v$SEMVERBOT_VERSION/sbot-linux-amd64
          chmod +x bin/sbot

      - name: make venv
        run: python -m venv venv

      - name: activate venv
        run: . venv/bin/activate

      - name: release
        run: sbot release version

      - name: push
        run: sbot push version

      - name: generate version file
        run: invoke get-version

      - name: deploy
        run: invoke deploy
